### ISSUE TITLE
Any chance of updating to work with Rd2024.3.x ?

### ISSUE THREAD

**Issue by surgicalcoder** [seclerp/rider-msbuild-devkit#34]
As title says, any chance of getting this updated please? :smile:

**Comment by seclerp** [comment]
Hi @surgicalcoder, that's a nice catch! I was busy recently but I will try to find some time to upgrade all my plugins to support Rider 2024.3. Sorry for the inconvenience! I'm going to close this issue once it gets merged so you can continue to watch it for updates.

Happy holidays! 🎄
